# Generated by Django 4.0.1 on 2022-02-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftNEP', '0002_product_seller_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='mobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
