# Generated by Django 4.0.1 on 2022-02-09 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thriftNEP', '0006_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
