# Generated by Django 4.0.2 on 2022-05-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thriftNEP', '0009_alter_seller_mobile_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='help_description',
            new_name='des',
        ),
    ]
